datasets:
  train:
    # data loadecr
    num_worker_per_gpu: 10
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    eta_min: !!float 1e-5
    periods: [96600, 193200, 289800]
    restart_weights: [1, 0.5, 0.25]

  total_iter: 289800
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
